decalage2/olefile

olefile/olefile.py
Storage nodes may store a clsid which identifies the application that can read/write to these data structures. It helps to identify storage parts of unknown origin, e.g. embedded OLE objects.
=> Add method to retrieve clsid for stream/storage

olefile/olefile.py
Remove a spurious repr() that sneaked into #46 that should not have been there in the first place.
=> Remove spurious repr() in getclsid()

.editorconfig
EditorConfig is built in to several popular editors, and many others have a plugin. It lets you define some simple common code standard things regarding text formatting and takes care of them automatically in the editor.
Get your plugin here: http://editorconfig.org
This will help with https://github.com/decalage2/olefile/issues/50.
This is the file from Pillow, feel free to add/remove extensions as necessary for this project.
=> Let EditorConfig take care of some basic formatting

setup.cfg
This'll produce py2.py3-none-any wheels when built with `pip wheel`.  I didn't see any custom py2 / py3 setup code so this should be correct?
=> olefile is a pure python library

install.bat, olefile/olefile.py, setup.py
I would humbly like to suggest the project not include extremely lengthy CHANGELOG and TODO type comments in the code. Some of these comments are describing changes from 2005. In my opinion, this is not the best place to store such comments it is better served by other tools such as the git log or a [CHANGELOG file](http://keepachangelog.com/en/0.3.0/). Big TODO items are better served through [issues](https://github.com/decalage2/olefile/issues) or a project roadmap.
For new contributors reading the code, these comments are very unconventional and make it difficult to read the code as there is so much surrounding noise. I have removed them to help tidy up the code and
bring it in line with conventions and other Python libraries.
=> Remove all lengthy CHANGELOG, TODO type comments from source files

appveyor.yml
Here's the config to run the unit tests on a Windows CI, based on .travis.yml.
Please go to https://ci.appveyor.com/projects/new to add the decalage2/olefile repo, it's free for open source.
I've added the 32-bit and 64-bit versions of the main Python versions. I've left out 2.6 and 3.2 for now, because they'll need a bit of special handling to install unittest2 and coverage<4 respectively.
See https://ci.appveyor.com/project/hugovk/olefile/build/1.0.5 for an example build.
=> Test on Windows CI with AppVeyor

setup.cfg
Instead of "True", use 1. From the Wheel documentation:
https://wheel.readthedocs.io/en/stable/index.html
> Typically, projects would not specify Python tags on the command line, but would use setup.cfg to set them as a project default:
>
> ```
> [bdist_wheel]
> universal = 1
> ```
=> Specify universal wheel as "universal = 1" as documneted

tests/test_olefile.py
Avoids testing against the deprecated import. Instead uses the expect package.
=> Import the real package in tests, not the deprecated module

setup.py
The default encoding used by `open` is system-dependent, and defaults to ASCII in many cases. Declaring the encoding explicitly prevents any issue from occurring.
=> Explicitly declare the README encoding in setup.py

.travis.yml, setup.py
Python 3.7 is in beta, so start testing it. The next quarterly Pillow release will support it. 
Currently `3.7-dev` is the latest on Travis CI, this can be switched when `3.7` is available. [AppVeyor](https://www.appveyor.com/docs/build-environment/#python) doesn't yet have it.
https://www.python.org/dev/peps/pep-0537/#schedule
=> Add Python 3.7

olefile/olefile.py
Both `range()` and `xrange()` expects integer as parameter, not float.
num_props is set to the second argument of min() when data length / 8 is lesser
than num_props, what is float, not int.
>>> 16/8
2.0
=> Fix TypeError: 'float' object cannot be interpreted as an integer.

olefile/olefile.py, tests/test_olefile.py
This adds a context manager to OleFileIO enabling users to write
```
with olefile.OleFileIO('myfile') as ole:
...
```
and not having to worry about remembering to close the file.
=> Add context manager to OleFileIO

olefile/olefile.py
We have to check whether current child was already used before we go to its
left child.
Before:
E.g. Root = 0 -> Left child of 0 = 1 -> Left child of 1 = 0 -> 1 -> infinite recursion.
Now:
E.g. Root = 0 -> Left child of 0 = 1 -> Left child of 1 = 0 -> been here, go back!
=> Fix RuntimeError: maximum recursion depth exceeded #61.

setup.py
distutils is not recommended for use and unnecessary for modern Python
environments. Use only setuptools instead. From
https://docs.python.org/3/library/distutils.html:
> Most Python users will not want to use this module directly, but
> instead use the cross-version tools maintained by the Python Packaging
> Authority. In particular, setuptools is an enhanced alternative to
> distutils ...
>
> The recommended pip installer runs all setup.py scripts with
> setuptools, even if the script itself only imports distutils. Refer to
> the Python Packaging User Guide for more information.
=> Drop legacy distutils in setup.py

.travis.yml, appveyor.yml, doc/History.rst, doc/Install.rst, olefile/__init__.py, olefile/olefile.py, setup.py, winbuild/appveyor_install_pypy.cmd
Python 3.4 reached [EOL on 2019-03-16](https://devguide.python.org/#status-of-python-branches) and is no longer supported by the core Python team.
Pillow dropped support in the most recent 6.0.0 release: https://github.com/python-pillow/Pillow/pull/3596.
The tested PyPy version is also updated on AppVeyor.
=> Drop support for EOL Python 3.4

olefile/olefile.py
* Added new exceptions that are specific to this module.
+ `OleFileError`: Generic error for this module.
+ `NotOleFileError`: Error to be raised when the input is not an OLE2 structured storage file.
* Changed the default exception raised by `OleFileIO._raise_defect` from `IOError` to `OleFileError`.
=> Modified exceptions

olefile/olefile.py
get_document_variables function extracts all stored document variables from a doc file. 
Variables that are created by (ActiveDocument.Variables.Add)
https://support.microsoft.com/en-us/help/306281/how-to-store-and-retrieve-variables-in-word-documents
=> Extractcustomvars

olefile/olefile.py, tests/test_olefile.py
This solves issue #120 ("Clarify who owns fp")
Clarify that fp is owned by whoever created it. Meaning that if an OleFileIO was created/opened with an open file handle as argument, it will never close it. On the other hand, if an OleFileIO was created/opened with a filename, it opens that file internally and therefore takes care to always close the handle.
However, the user of an OleFileIO is responsible for calling close() on it. If she fails to do so a warning is issued to help improve caller code.
Unittests verify that this works as expected and will work in the future. Doc strings also include hints.
This avoids ResourceWarnings caused by unclosed file handles in OleFileIO.
=> Close fp if we created it

winbuild/appveyor_install_pypy.cmd
This fixes the Windows PyPy build.
* Before: https://ci.appveyor.com/project/hugovk/olefile/builds/34763513
---
https://bitbucket.org/pypy/pypy/ now says:
> ### Repository unavailable
> Bitbucket no longer supports Mercurial repositories.
PyPy source and issues has moved to https://foss.heptapod.net/pypy/pypy
Downloads are now at downloads.python.org:
* https://www.pypy.org/download.html
* https://downloads.python.org/pypy/
=> CI: Fix PyPy download link

.travis.yml
Python 3.9.0 final is due out in October. The first release candidate is out, and it's strongly recommended to test third-party libraries on it, to both make sure the library is ready for 3.9, and to help test 3.9 itself.
https://www.python.org/dev/peps/pep-0596/
=> Test Python 3.9-dev
